{
	"candidate": "CVE-2024-32879",
	"description": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
	"priority": "medium",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2024-32879",
		"https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-2gr8-3wc7-xhj3",
		"https://github.com/python-social-auth/social-app-django/pull/566",
		"https://github.com/python-social-auth/social-app-django/commit/31c3e0c7edb187004d8abbde7e9c4f7ef9098138"
	],
	"public_date": "2024-04-25",
	"packages": {
		"devel": {
			"python-social-auth": {
				"name": "python-social-auth",
				"status": "DNE"
			}
		},
		"esm-apps/bionic": {
			"python-social-auth": {
				"name": "python-social-auth",
				"status": "needs-triage"
			}
		},
		"esm-apps/xenial": {
			"python-social-auth": {
				"name": "python-social-auth",
				"status": "needs-triage"
			}
		},
		"focal": {
			"python-social-auth": {
				"name": "python-social-auth",
				"status": "DNE"
			}
		},
		"jammy": {
			"python-social-auth": {
				"name": "python-social-auth",
				"status": "DNE"
			}
		},
		"mantic": {
			"python-social-auth": {
				"name": "python-social-auth",
				"status": "DNE"
			}
		},
		"upstream": {
			"python-social-auth": {
				"name": "python-social-auth",
				"status": "needs-triage"
			}
		}
	}
}
