{
	"candidate": "CVE-2019-10904",
	"description": "Roundup 1.6 allows XSS via the URI because frontends/roundup.cgi and roundup/cgi/wsgi_handler.py mishandle 404 errors.",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N [6.1 MEDIUM]"
	},
	"bugs": [
		"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926587"
	],
	"references": [
		"https://github.com/python/bugs.python.org/issues/34",
		"https://issues.roundup-tracker.org/issue2551035",
		"https://bitbucket.org/python/roundup/commits/51682dc2cd7e28421d749117c25bec58f632ee5f",
		"https://bugs.python.org/issue36391",
		"https://www.openwall.com/lists/oss-security/2019/04/05/1",
		"https://www.cve.org/CVERecord?id=CVE-2019-10904"
	],
	"public_date": "2019-04-06 20:29:00 UTC",
	"packages": {
		"bionic": {
			"roundup": {
				"name": "roundup",
				"status": "DNE"
			}
		},
		"cosmic": {
			"roundup": {
				"name": "roundup",
				"status": "DNE"
			}
		},
		"devel": {
			"roundup": {
				"name": "roundup",
				"status": "DNE"
			}
		},
		"disco": {
			"roundup": {
				"name": "roundup",
				"status": "DNE"
			}
		},
		"esm-apps/xenial": {
			"roundup": {
				"name": "roundup",
				"status": "released",
				"note": "1.4.20-1.1+deb8u2build0.16.04.1"
			}
		},
		"precise/esm": {
			"roundup": {
				"name": "roundup",
				"status": "DNE"
			}
		},
		"trusty": {
			"roundup": {
				"name": "roundup",
				"status": "ignored",
				"note": "end of standard support"
			}
		},
		"trusty/esm": {
			"roundup": {
				"name": "roundup",
				"status": "DNE",
				"note": "trusty was needed"
			}
		},
		"upstream": {
			"roundup": {
				"name": "roundup",
				"status": "needs-triage"
			}
		},
		"xenial": {
			"roundup": {
				"name": "roundup",
				"status": "released",
				"note": "1.4.20-1.1+deb8u2build0.16.04.1"
			}
		}
	}
}
