{
  "candidate": "CVE-2015-5159",
  "description": "python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request.",
  "priority": "medium",
  "cvss": {
    "nvd": " CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]"
  },
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-5159",
    "https://bugzilla.redhat.com/show_bug.cgi?id=1245200",
    "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882"
  ],
  "public_date": "2018-10-30 18:29:00 UTC",
  "packages": {
    "bionic": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "not-affected",
        "note": "0.3.2-1"
      }
    },
    "cosmic": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "not-affected",
        "note": "0.3.2-1"
      }
    },
    "devel": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "not-affected",
        "note": "0.3.2-1"
      }
    },
    "esm-apps/bionic": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "not-affected",
        "note": "0.3.2-1"
      }
    },
    "esm-apps/xenial": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "not-affected",
        "note": "0.3.2-1"
      }
    },
    "precise/esm": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "DNE"
      }
    },
    "trusty": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "DNE"
      }
    },
    "trusty/esm": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "DNE"
      }
    },
    "upstream": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "released",
        "note": "0.3.2"
      }
    },
    "xenial": {
      "python-kdcproxy": {
        "name": "python-kdcproxy",
        "status": "not-affected",
        "note": "0.3.2-1"
      }
    }
  }
}
