{
	"candidate": "CVE-2012-1502",
	"description": "Double free vulnerability in the PyPAM_conv in PAMmodule.c in PyPam 0.5.0 and earlier allows remote attackers to cause a denial of service (application crash) or possibly execute arbitrary code via a NULL byte in a password string.",
	"priority": "medium",
	"bugs": [
		"https://launchpad.net/bugs/949218"
	],
	"references": [
		"https://ubuntu.com/security/notices/USN-1395-1",
		"https://www.cve.org/CVERecord?id=CVE-2012-1502"
	],
	"assigned_to": "mdeslaur",
	"discovered_by": "Markus Vervier",
	"public_date": "2012-06-16 00:55:00 UTC",
	"public_date_at_usn": "2012-03-08",
	"packages": {
		"devel": {
			"python-pam": {
				"name": "python-pam",
				"status": "released",
				"note": "0.4.2-12.2ubuntu4"
			}
		},
		"hardy": {
			"python-pam": {
				"name": "python-pam",
				"status": "ignored",
				"note": "end of life"
			}
		},
		"lucid": {
			"python-pam": {
				"name": "python-pam",
				"status": "released",
				"note": "0.4.2-12.1ubuntu1.10.04.1"
			}
		},
		"maverick": {
			"python-pam": {
				"name": "python-pam",
				"status": "released",
				"note": "0.4.2-12.1ubuntu1.10.10.1"
			}
		},
		"natty": {
			"python-pam": {
				"name": "python-pam",
				"status": "released",
				"note": "0.4.2-12.2ubuntu2.11.04.1"
			}
		},
		"oneiric": {
			"python-pam": {
				"name": "python-pam",
				"status": "released",
				"note": "0.4.2-12.2ubuntu2.11.10.1"
			}
		},
		"upstream": {
			"python-pam": {
				"name": "python-pam",
				"status": "needs-triage"
			}
		}
	}
}
