{
	"candidate": "CVE-2012-3444",
	"description": "The get_image_dimensions function in the image-handling functionality in Django before 1.3.2 and 1.4.x before 1.4.1 uses a constant chunk size in all attempts to determine dimensions, which allows remote attackers to cause a denial of service (process or thread consumption) via a large TIFF image.",
	"notes": {
		"mdeslaur": "possible regression, see LP: #1031733"
	},
	"priority": "medium",
	"bugs": [
		"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=683364",
		"https://bugs.launchpad.net/ubuntu/+source/python-django/+bug/1031733"
	],
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3444",
		"https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued/",
		"http://www.openwall.com/lists/oss-security/2012/07/31/1",
		"http://www.openwall.com/lists/oss-security/2012/07/31/2",
		"https://ubuntu.com/security/notices/USN-1560-1"
	],
	"discovered_by": "Jeroen Dekkers",
	"public_date": "2012-07-31 17:55:00 UTC",
	"public_date_at_usn": "2012-07-31",
	"packages": {
		"devel": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected",
				"note": "1.4.1-1",
				"patches": [
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2012/dsa-2529"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446"
					}
				]
			}
		},
		"hardy": {
			"python-django": {
				"name": "python-django",
				"status": "ignored",
				"note": "end of life",
				"patches": [
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2012/dsa-2529"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446"
					}
				]
			}
		},
		"lucid": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.1.1-2ubuntu1.5",
				"patches": [
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2012/dsa-2529"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446"
					}
				]
			}
		},
		"natty": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.2.5-1ubuntu1.2",
				"patches": [
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2012/dsa-2529"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446"
					}
				]
			}
		},
		"oneiric": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3-2ubuntu1.3",
				"patches": [
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2012/dsa-2529"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446"
					}
				]
			}
		},
		"precise": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3.1-4ubuntu1.2",
				"patches": [
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2012/dsa-2529"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446"
					}
				]
			}
		},
		"upstream": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3.2,1.4.1",
				"patches": [
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2012/dsa-2529"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446"
					}
				]
			}
		}
	}
}
