{
	"candidate": "CVE-2021-46823",
	"description": "python-ldap before 3.4.0 is vulnerable to a denial of service when ldap.schema is used for untrusted schema definitions, because of a regular expression denial of service (ReDoS) flaw in the LDAP schema parser. By sending crafted regex input, a remote authenticated attacker could exploit this vulnerability to cause a denial of service condition.",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H [6.5 MEDIUM]"
	},
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-46823",
		"https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm",
		"https://exchange.xforce.ibmcloud.com/vulnerabilities/221507",
		"https://ubuntu.com/security/notices/USN-5508-1"
	],
	"assigned_to": "leosilva",
	"public_date": "2022-06-18 16:15:00 UTC",
	"public_date_at_usn": "2022-06-18 16:15:00 UTC",
	"packages": {
		"bionic": {
			"python-ldap": {
				"name": "python-ldap",
				"status": "released",
				"note": "3.0.0-1ubuntu0.2",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d"
					}
				]
			}
		},
		"devel": {
			"python-ldap": {
				"name": "python-ldap",
				"status": "not-affected",
				"note": "3.4.0-2",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d"
					}
				]
			}
		},
		"esm-infra/bionic": {
			"python-ldap": {
				"name": "python-ldap",
				"status": "released",
				"note": "3.0.0-1ubuntu0.2",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d"
					}
				]
			}
		},
		"focal": {
			"python-ldap": {
				"name": "python-ldap",
				"status": "released",
				"note": "3.2.0-4ubuntu2.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d"
					}
				]
			}
		},
		"impish": {
			"python-ldap": {
				"name": "python-ldap",
				"status": "released",
				"note": "3.2.0-4ubuntu5.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d"
					}
				]
			}
		},
		"jammy": {
			"python-ldap": {
				"name": "python-ldap",
				"status": "released",
				"note": "3.2.0-4ubuntu7.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d"
					}
				]
			}
		},
		"upstream": {
			"python-ldap": {
				"name": "python-ldap",
				"status": "released",
				"note": "3.4.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d"
					}
				]
			}
		}
	}
}
