{
  "candidate": "CVE-2013-2098",
  "description": "** REJECT **  DO NOT USE THIS CANDIDATE NUMBER.  ConsultIDs: CVE-2013-2099. Reason: This candidate is a duplicate of CVE-2013-2099.  Notes: All CVE users should reference CVE-2013-2099 instead of this candidate.  All references and descriptions in this candidate have been removed to prevent accidental usage.",
  "notes": {
    "mdeslaur": "This CVE is for the python-backports-ssl_match_hostname package. CVE-2013-2099 is for python itself."
  },
  "priority": "low",
  "bugs": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=963186",
    "https://bugs.launchpad.net/ubuntu/+source/bzr/+bug/1182124",
    "http://bugs.python.org/issue17980"
  ],
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-2098",
    "http://www.openwall.com/lists/oss-security/2013/05/16/5",
    "https://bugzilla.redhat.com/show_bug.cgi?id=963260"
  ],
  "discovered_by": "Florian Weimer",
  "public_date": "2013-10-09 14:53:00 UTC",
  "packages": {
    "devel": {
      "python2.6": {
        "name": "python2.6",
        "status": "DNE"
      }
    },
    "lucid": {
      "python2.6": {
        "name": "python2.6",
        "status": "not-affected",
        "note": "code-not-present"
      }
    },
    "precise": {
      "python2.6": {
        "name": "python2.6",
        "status": "DNE"
      }
    },
    "quantal": {
      "python2.6": {
        "name": "python2.6",
        "status": "DNE"
      }
    },
    "raring": {
      "python2.6": {
        "name": "python2.6",
        "status": "DNE"
      }
    },
    "upstream": {
      "python2.6": {
        "name": "python2.6",
        "status": "needs-triage"
      }
    }
  }
}
